[build]
  base = "."  # Root directory of your project
  publish = "public"  # Directory to publish after the build. If your app doesn't have a build output folder, leave it as "." (the root folder).
  command = "npm install"  # Adjust if you have a build process, like if you're using a bundler like Webpack or a frontend framework.
  
[build.environment]
  NODE_VERSION = "20.11.1"  # Specify the Node.js version you want to use (you can change this based on your app's needs).

[[redirects]]
  from = "/*"  # Redirect all requests to index.html
  to = "/index.html"
  status = 200  # For static sites (adjust if necessary for routes)
